NewsPro/NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from news import views


router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'authors', views.AuthorViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('news.urls')),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

NewsPro/NewsPaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, PostCreate, PostUpdate, PostDelete, ArticleCreate, ArticleUpdate, \
    ArticleDelete, CategoryListView, subscribe

urlpatterns = [
    path('news/', PostList.as_view(), name='post_list'),
    path('news/<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('news/search/', PostSearch.as_view()),
    path('news/create/', PostCreate.as_view(), name='post_create'),
    path('news/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),

    path('articles/create/', ArticleCreate.as_view(), name='article_create'),
    path('articles/<int:pl>/edit/', ArticleUpdate.as_view(), name='article_create'),
    path('articles/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),

    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),

]

NewsPro/NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPro/NewsPaper/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}" ?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPro/NewsPaper/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPro/NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
    <h3>{{ posts|length }}</h3>
    {% if is_not_subscriber %}
        <a href="{% url 'subscribe' category.id %}">Подписаться</a>
    {% endif %}
   <hr>

   {% if perms.news.add_post %}
   <a href="{% url 'post_create' %}">Добавить новость</a>
   {% endif %}

   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата создания</td>
               <td>Текст</td>
               <td>Категория</td>
               <td>Тип</td>

               {% if perms.news.change_post or perms.news.delete_post %}
               <td>Действия</td>
               {% endif %}
           </tr>

           {% for post in category_news_list %}
           <tr>
               <td>{{ post.title }}</td>
               <td>{{ post.dateCreation|date:'d. M. Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
               <td>{% for category in post.postCategory.all %}
               <a href="{% url 'category_list' category.id %}">{{ category.name }}</a>
                   {% endfor %}
               </td>
               <td>{{ post.categoryType }}</td>
               <td>
                   {% if perms.news.change_post %}
               <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
               <a href="{% url 'post_delete' post.id %}">Удалить</a>
                   {% endif %}
                   </td>
               </td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>

   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}

            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}

            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPro/NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новые статьи за последнюю неделю!</h2>
<ul>
    {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

NewsPro/NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}
{% load cache %}
{% block title %}
Post
{% endblock title %}

{% block content %}
{% cache 30 details %}
    <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата создания</td>
               <td>Текст</td>
           </tr>

           <tr>
               <td>{{ post.title }}</td>
               <td>{{ post.dateCreation|date:'d. M. Y' }}</td>
               <td>{{ post.text }}</td>
           </tr>

       </table>
{% endcache %}
{% endblock content %}

NewsPro/NewsPaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPro/NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}" ?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPro/NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPro/NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load tz %}
{% load custom_filters %}
{% load custom_tags %}
{% load cache %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
{% cache 5 main %}
        <h1>{% trans 'Все новости' %}</h1>
        <h3>{{ posts|length }}</h3>
<hr>

   {% if perms.news.add_post %}
   <a href="{% url 'post_create' %}">{% trans 'Добавить новость' %}</a>
   {% endif %}

   {% if posts %}
       <table>
           <tr>
               <td>{% trans 'Заголовок' %}</td>
               <td>{% trans 'Дата создания' %}</td>
               <td>{% trans 'Текст' %}</td>
               <td>{% trans 'Категория' %}</td>
               <td>{% trans 'Тип' %}</td>

               {% if perms.news.change_post or perms.news.delete_post %}
               <td>{% trans 'Действия' %}</td>
               {% endif %}
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title }}</td>
               <td>{{ post.dateCreation|date:'d. M. Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
               <td>{% for category in post.postCategory.all %}
               <a href="{% url 'category_list' category.id %}">{{ category.name }}</a>
                   {% endfor %}
               </td>
               <td>{{ post.categoryType }}</td>
               <td>
                   {% if perms.news.change_post %}
               <a href="{% url 'post_update' pk=post.id %}">{% trans 'Изменить' %}</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
               <a href="{% url 'post_delete' post.id %}">{% trans 'Удалить' %}</a>
                   {% endif %}
                   </td>
               </td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>{% trans 'Новостей нет!' %}</h2>

   {% endif %}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}

                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}

   {% endif %}

   {{ page_obj.number }}
        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}

                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
   {% endif %}
{% endcache %}
{% endblock content %}

NewsPro/NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
    <h3>{{ posts|length }}</h3>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>
   <hr>
   {% if search %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата создания</td>
               <td>Текст</td>
               <td>Категория</td>
           </tr>

           {% for post in search %}
           <tr>
               <td>{{ post.title }}</td>
               <td>{{ post.dateCreation|date:'d. M. Y' }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>
               <td>{% for category in post.postCategory.all %}
               {{ category.name }}
                   {% endfor %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>

   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}

            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}

            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPro/NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1>{{ message }} {{ category }}</h1>
{% endblock content %}

NewsPro/NewsPaper/templates/swagger.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "//lms-cdn.skillfactory.ru/assets/courseware/v1/a084991b3a1596be3ed570c65c56393c/asset-v1:SkillFactory+FPW-2.0+27AUG2020+type@asset+block/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>